---
- name: Delete Openshift
  hosts: openshift
  become: yes

  tasks:
    - name: check for Openshift
      stat:
          path: /usr/bin/oc
      register: oc_result
      become: True

    - name: Stop Openshift 
      shell: oc cluster down
      register: task_result
      ignore_errors: yes
      when: oc_result.stat.exists == True

  
    - file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/bin/oc


    - pause: seconds=15
      when: oc_result.stat.exists == True

    
    - shell: | 
        mount | grep 'openshift.local.volumes' | awk '{ print $3}' | xargs -l -r umount
        docker images  | grep openshift | awk '{ print $3}' | xargs -l -r docker rmi
        rm -rf /var/lib/origin/*
        rm -rf ~/.kube
        rm -rf .kube
      when: oc_result.stat.exists == True


      

      