---
- name: Prep Avi Controller Config
  hosts: kubernetes
  become: True

  tasks:
    - name: Retrieve Service Account Secret Name
      shell: kubectl describe serviceaccount avi -n default | grep Mountable | awk '{print $3'}
      register: srvc_account_secret_name


    - debug:
        msg: "{{ srvc_account_secret_name.stdout }}"


    - name: Retrieve Service Account Secret Name
      shell: "kubectl describe secret {{ srvc_account_secret_name.stdout }} -n default | grep token: | awk '{print $2'}"
      register: srvc_account_token


    - debug:
        msg: "{{ srvc_account_token.stdout }}"


    - name: Prepare Controller config
      shell: |
          cp template_setup.json setup.json
          sed -i "s/REPLACE-TOKEN/{{ srvc_account_token.stdout }}/g" setup.json
          sed -i "s/REPLACE-IP/{{ ansible_default_ipv4.address }}/g" setup.json
