avi_config:
  pool:
    - name: Avi-Demo-pool
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      health_monitor_refs:
        - "/api/healthmonitor?name=System-HTTP"
      servers:
        - hostname: "demoserver1.avinet"
          #resolve_server_by_dns: true
          ip:
             addr: "169.254.127.200"
             type: 'V4'
        - hostname: "demoserver1.avinet"
          #resolve_server_by_dns: true
          ip:
             addr: "169.254.127.201"
             type: 'V4'
        - hostname: "demoserver3.avinet"
          #resolve_server_by_dns: true
          ip:
             addr: "169.254.127.202"
             type: 'V4'
        - hostname: "demoserver4.avinet"
          #resolve_server_by_dns: true
          ip:
             addr: "169.254.127.203"
             type: 'V4'
    - name: Downloads-pool
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      health_monitor_refs:
        - "/api/healthmonitor?name=System-HTTP"
      servers:
        - ip:
             addr: "169.254.127.200"
             type: 'V4'
    - name: ContactUs-pool
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      health_monitor_refs:
        - "/api/healthmonitor?name=System-HTTP"
      servers:
        - ip:
             addr: "169.254.127.200"
             type: 'V4'

  httppolicyset:
    - name: "Avi-Demo-httppolicy"
      http_request_policy:
        rules:
          - index: 1
            enable: true
            name: "Downloads rule"
            match:
              path:
                match_case: INSENSITIVE
                match_str:
                  - /downloads
                match_criteria: EQUALS
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
              pool_ref: "/api/pool?name=Downloads-pool"
          - index: 2
            enable: true
            name: "Contact us rule"
            match:
              path:
                match_case: INSENSITIVE
                match_str:
                  - /contactus
                match_criteria: CONTAINS
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
              pool_ref: "/api/pool?name=ContactUs-pool"
      is_internal_policy: false

  virtualservice:
    - name: Avi-Demo-VS
      services:
        - port: 80
        - port: 443
          enable_ssl: true
      application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
      ssl_key_and_certificate_refs:
        - "/api/sslkeyandcertificate?name=System-Default-Cert"
        - "/api/sslkeyandcertificate?name=System-Default-Cert-EC"

      pool_ref: '/api/pool?name=Avi-Demo-pool'
      vip:
        - ip_address:
            addr: "169.254.10.1"
            type: 'V4'
          vip_id: '1'
      http_policies:
        - index: 11
          http_policy_set_ref: '/api/httppolicyset?name=Avi-Demo-httppolicy'
      analytics_policy:
        udf_log_throttle: 0
        #enabled: true
        full_client_logs:
          duration: 0
          all_headers: false
          throttle: 0
          enabled: true
        metrics_realtime_update:
          duration: 0
          enabled: true
        significant_log_throttle: 0
        client_insights: PASSIVE
